### ISSUE TITLE
Face recognition

### ISSUE THREAD

**Issue by dungnt0305** [Linzaer/Face-Track-Detect-Extract#11]
Hi, thanks for amazing code.

After get cropped = frame[bb[1]:bb[3], bb[0]:bb[2], :].copy()
i saved it to backend.
How can i know images for per ID tracker for face recognition?

Thanks so much.

**Comment by Linzaer** [comment]
I save the best face pic in floder './facepics'.Each tracker has a field named 'id', so you can get it and  pass it  to the function for saving file.

**Comment by dungnt0305** [comment]
Thanks for your reply.
I mean.
I save all cropped face to ID-tracker folders have structure :
Id 1 : 
--- Id1_1.jpg
--- Id2_2.jpg
--- Id3_3.jpg
ID 2 
--- Id2_1.jpg
--- Id2_2.jpg
--- Id2_3.jpg

How can i do that.
Thanks so much

**Comment by SabraHashemi** [comment]
> Thanks for your reply.
> I mean.
> I save all cropped face to ID-tracker folders have structure :
> Id 1 :
> --- Id1_1.jpg
> --- Id2_2.jpg
> --- Id3_3.jpg
> ID 2
> --- Id2_1.jpg
> --- Id2_2.jpg
> --- Id2_3.jpg
> 
> How can i do that.
> Thanks so much

did you success to do this?
