### ISSUE TITLE
多目标跟踪保存图像错误

### ISSUE THREAD

**Issue by nerddd** [Linzaer/Face-Track-Detect-Extract#16]
在进行多人脸检测跟踪时，发现可以检测跟踪到的人脸（有矩形框显示框住了），但是并未在facepic中成功保存下来（包括一些质量很好的正脸也没有保存），只保存了部分人脸

**Comment by nerddd** [comment]
原因是有些人脸变化很小，一直到视频结束都没断track，所以这些人脸都没有保存下来，请问有解决办法么

**Comment by Linzaer** [comment]
#13

**Comment by Linzaer** [comment]
你可以在视频结束读取不到图像break之前，通知追踪器强制销毁保存。

**Comment by nerddd** [comment]
嗯嗯，解决啦，谢谢~

**Comment by Linzaer** [comment]
不客气
