### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bmabir17** [Linzaer/Face-Track-Detect-Extract#2]
I tried to run sart.py but it gives the mentioned error. I tracked the source of the error down to `from filterpy.kalman import KalmanFilter` in src>sort.py 
I have all the dependencies required for the project with anaconda

**Comment by Linzaer** [comment]
Sorry ,I haven't had this problem.According to what you said,you should make sure the module **filterpy** is installed successfully. This code just uses the **KalmanFilter** in **filterpy**.I guess it's a memory error like the limitation of the stack size in your os or something else  and you can use **gdb** to debug it.
