### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by fengyanWang** [Linzaer/Face-Track-Detect-Extract#30]
你好，我在运行你代码的时候出现了如下的错误，请问应该如何修改呢？非常感谢！！望回复！！

![image](https://user-images.githubusercontent.com/36984088/131979246-4637fa94-bc24-4f48-a700-4d4e0e2a705a.png)

**Comment by xliao0** [comment]
我也遇到了一模一样的错误，请问您后来有找到错误原因和解决方法吗？

**Comment by lyyiangang** [comment]
comment ``` from sklearn.utils.linear_assignment_ import linear_assignment``` and use following ```linear_assignment``` function
```python
# from sklearn.utils.linear_assignment_ import linear_assignment
 
def linear_assignment(cost_matrix):
    from scipy.optimize import linear_sum_assignment
    x, y = linear_sum_assignment(cost_matrix)
    return np.array(list(zip(x, y)))
```
