### ISSUE TITLE
多目标跟踪方法

### ISSUE THREAD

**Issue by rochou** [Linzaer/Face-Track-Detect-Extract#5]
大佬用的多目标跟踪能简单说一下么？我看见一个卡尔曼滤波跟踪，是不是特定情况可能会发生跟踪错乱的情况呢？

**Comment by Linzaer** [comment]
开始第一帧全局检测人脸，然后对检测出的多人脸采用卡尔曼追踪，每个人脸分配一个追踪器进行逐帧追踪，之后每隔若干帧进行一次全局人脸检测来和之前的追踪人脸进行IOU重叠度匹配，若高于阈值则用检测出来的人脸进行纠偏继续追踪，否则移除追踪器，之后重复循环迭代。跟踪错乱和画面场景有很大关系，比如画面跳帧、人脸质量低、人脸形变大、人脸密集导致重叠度高、人物移速过快、人脸检测模型检测错误等等，都有可能影响追踪效果，所以不能一概而论。

**Comment by rochou** [comment]
好的，多谢大佬指点
